staging: qcacld-3.0: use INIT_COMPLETION macro from CNSS WLAN Host
fix compilation error after new tag LA.UM.8.2.r1-06300-sdm660.0 merges:

../drivers/staging/qcacld-3.0/components/pkt_capture/core/src/wlan_pkt_capture_mon_thread.c:296:5: error: implicit declaration of function 'INIT_COMPLETION'
      [-Werror,-Wimplicit-function-declaration]
                                INIT_COMPLETION(mon_ctx->resume_mon_event);

we can't use INIT_COMPLETION macro since 62026aedaacedbe1ffe94a3599ad4acd8ecdf587, but caf still using it for qca-wifi-host-cmn (CNSS WLAN Host).

Change-Id: Ib84d8a9688fd82e21f21ff323f31c76cdcd11e5a